# Site settings
title: blog.pixus.io
email: skorulis@pixus.io
description: > # this means to ignore newlines until "baseurl:"
  Pixus is a content sharing network built on top of webRTC
url: "http://blog.pixus.io" # the base hostname & protocol for your site
twitter_username: skorulis
github_username:  skorulis

# Build settings
markdown: kramdown
